# Generated by Django 5.0.6 on 2024-07-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
